# Generated by Django 5.1.2 on 2024-10-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equilibriumapp', '0002_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equilibriumapp.medico'),
        ),
    ]
