# Generated by Django 5.1.2 on 2024-10-21 19:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equilibriumapp', '0009_alter_medico_cpf_alter_medico_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicos', models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='equilibriumapp.medico')),
            ],
        ),
    ]
